# Generated by Django 4.1.7 on 2023-03-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField()),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HiredEmployeesRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hired_employee_id', models.IntegerField()),
                ('name', models.TextField()),
                ('datetime', models.TextField()),
                ('department_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobsRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HiredEmployees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('datetime', models.TextField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.departments')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.jobs')),
            ],
        ),
    ]
