# Generated by Django 4.1.7 on 2023-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.TextField(blank=True),
        ),
    ]
